DefaultLanguage: ja_JP

Motd:
- "&eWelcome To &2Honobono &8Server &r&e!! &l[1.8.x]"

Elevator:
- REDSTONE_BLOCK:8
- LAPIS_BLOCK:16
- IRON_BLOCK:32
- EMERALD_BLOCK:64
- GOLD_BLOCK:128
- DIAMOND_BLOCK:256

OverridePluginCommand:
    Enable: true
    Content: |
        "てすと"

# <world>, <message>, <player>, <prefix>. <suffix>
ChatFormat: "[<prefix>]<<player>> <message>"

EndWorld: TheEnd

PassWordSign:
    - "Tutorial:test"